# Generated by Django 5.0.6 on 2024-06-18 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='materia',
            field=models.CharField(default='Matemáticas', max_length=100),
        ),
    ]
