# Generated by Django 5.0.6 on 2024-06-18 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0003_alter_teacher_materia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='materia',
        ),
        migrations.AddField(
            model_name='teacher',
            name='grado',
            field=models.CharField(default='Primero', max_length=100),
        ),
    ]
