# Generated by Django 5.0.6 on 2024-06-21 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0005_alter_teacher_grado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('document_number', models.IntegerField(unique=True)),
                ('grade', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=20)),
                ('tutor_name', models.CharField(max_length=50)),
                ('tutor_number', models.IntegerField()),
            ],
        ),
    ]
