# Generated by Django 5.0.6 on 2024-06-21 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0007_student_birth_date_student_registration_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
