# Generated by Django 5.0.6 on 2024-06-21 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0009_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('espanol', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('matematicas', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('ingles', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('religion', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('sociales', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('etica', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('edu_fisica', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escuela.student')),
            ],
        ),
    ]
