# Generated by Django 5.0.6 on 2024-06-21 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0010_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
